//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eNarudžba
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hrana
    {
        public Hrana()
        {
            this.HranaSastojci = new HashSet<HranaSastojci>();
            this.komentariHrana = new HashSet<komentariHrana>();
            this.NarudzbaHrana = new HashSet<NarudzbaHrana>();
        }
    
        public int IDhrana { get; set; }
        public string Naziv { get; set; }
        public decimal Cijena { get; set; }
        public int IDvelicinaHrane { get; set; }
    
        public virtual VelicinaHrane VelicinaHrane { get; set; }
        public virtual ICollection<HranaSastojci> HranaSastojci { get; set; }
        public virtual ICollection<komentariHrana> komentariHrana { get; set; }
        public virtual ICollection<NarudzbaHrana> NarudzbaHrana { get; set; }
    }
}
