//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eNarudžba
{
    using System;
    using System.Collections.Generic;
    
    public partial class NarudzbaStatus
    {
        public int IDnarudzbaStatus { get; set; }
        public int IDnarudzba { get; set; }
        public int IDstatus { get; set; }
        public System.DateTime VrijemeKreiranjaStatusa { get; set; }
    
        public virtual Narudzba Narudzba { get; set; }
        public virtual Status Status { get; set; }
    }
}
