//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eNarudžba
{
    using System;
    using System.Collections.Generic;
    
    public partial class NarudzbaHrana
    {
        public int IDnarudzbaHrana { get; set; }
        public int IDnarudzba { get; set; }
        public int IDhrana { get; set; }
    
        public virtual Hrana Hrana { get; set; }
        public virtual Narudzba Narudzba { get; set; }
    }
}
