//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eNarudžba
{
    using System;
    using System.Collections.Generic;
    
    public partial class NarudzbaPice
    {
        public int IDnarudzbaPice { get; set; }
        public int IDnarudzbe { get; set; }
        public int IDpice { get; set; }
        public int Kolicina { get; set; }
    }
}
