//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eNarudžba
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pice
    {
        public Pice()
        {
            this.komentariPice = new HashSet<komentariPice>();
        }
    
        public int IDpice { get; set; }
        public string Naziv { get; set; }
        public decimal Cijena { get; set; }
        public double Kolicina { get; set; }
    
        public virtual ICollection<komentariPice> komentariPice { get; set; }
    }
}
