//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eNarudžba
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivremenaTablica
    {
        public int IDprivremenaTablica { get; set; }
        public string IDnarudzbaH { get; set; }
        public string IDnarudzbaP { get; set; }
        public string NazivHrana { get; set; }
        public string NazivPice { get; set; }
        public string CijenaHrana { get; set; }
        public string CijenaPice { get; set; }
        public string Opis { get; set; }
        public string Kolicina { get; set; }
    }
}
