//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eNarudžba
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sastojci
    {
        public Sastojci()
        {
            this.HranaSastojci = new HashSet<HranaSastojci>();
        }
    
        public int IDsastojci { get; set; }
        public string Naziv { get; set; }
        public int Kolicina { get; set; }
    
        public virtual ICollection<HranaSastojci> HranaSastojci { get; set; }
    }
}
