//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eNarudžba
{
    using System;
    using System.Collections.Generic;
    
    public partial class VelicinaHrane
    {
        public VelicinaHrane()
        {
            this.Hrana = new HashSet<Hrana>();
        }
    
        public int IDvelicinaHrane { get; set; }
        public string Opis { get; set; }
    
        public virtual ICollection<Hrana> Hrana { get; set; }
    }
}
